title: Zane G
description: Personal blog for sharing research and projects.
theme: jekyll-theme-midnight

# Optional social links (minima supports these)
author: Zane G
github_username: zaneGittins

# Enable posts
show_excerpts: true

# Optional but useful
markdown: kramdown
